### ISSUE TITLE
threebot flist builder [development_threebotbuilder]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#262]
story see threefoldtech/home#465

**Comment by rkhamis** [comment]
Threebotbuilder builds after release and merges, testing now that everything needed is in there

**Comment by RafyAmgadBenjamin** [comment]
* I have tested openresty builder
* I have tested lua builder
* I have tested zdb builder
* I have tested  sonic builder 
* I have tested jsx threebotbuilder
To make sure that they are working after the new changes

**Comment by RafyAmgadBenjamin** [comment]
* fixing an issue in python client 
* fixing an issue related to ```BuilderBaseClass``` in ```_touch``` method

**Comment by RafyAmgadBenjamin** [comment]
I have fixed Fixing ```prompt_toolkit``` version in ```InstallTools```
as when we install the latest version, it causes an error in the version in the toolkit and it no longer works. consequently, we can't start kosmos.

**Comment by BolaNasr** [comment]
Now Threebot builder sandbox works good , still have some issues in startup.toml

**Comment by RafyAmgadBenjamin** [comment]
While testing Sandbox with @BolaNasr  the sonic crashes but we couldn't reproduce this issue, we tested the Sonic installation standalone but it works well and the Threbot builder sandbox also worked well.

**Comment by gmachtel** [comment]
Can't be finished but some work can still be done ( add a feature to the threebotbuilder to create flist from this container & upload to hub).

**Comment by gmachtel** [comment]
Correct way implemented? To be discussed.

**Comment by rkhamis** [comment]
To build the sandbox, we will:
   1 - create 3bot container and build everything needed
   2 - ldd
   3 - rsync the sandbox to a new container. if everything works there, it means the sandbox is indeed complete
   4 - remove all uneed parts (for example /var)
   5 - create flist of this sandbox

**Comment by gmachtel** [comment]
As it's blocking critical issue https://github.com/threefoldtech/home/issues/429, I'll also put to prio_critical. Either dependency to be solved or this one is critical. To be discussed with @zaibon .

**Comment by RafyAmgadBenjamin** [comment]
I and @BolaNasr  were able to get a successful scenario related to the following steps
To build the sandbox, we will:
   1 - create 3bot container and build everything needed (Done)
```python
kosmos -p "j.builders.apps.threebot.install(reset=True)"
```
   2 - ldd (Done)
```python
kosmos -p 'j.tools.sandboxer.libs_sandbox(path= "/sandbox/bin") '
```

then we were able to start threebot server successfully 
```
kosmos -p "j.servers.threebot.local_start_default()"

```

**Comment by BolaNasr** [comment]
after rsync the sandbox to a new container. 
and make more tests we found this error 
![photo_2019-11-27_16-19-06](https://user-images.githubusercontent.com/10259267/69744092-330c8f00-1148-11ea-8ee2-0cba1f5d6cdc.jpg)

we are blocked in this error 
we Try 
1- sandbox python , threebot  and all dependencies 
2- make Ldd of all binaries 
and still have more problems in start kosmos

**Comment by BolaNasr** [comment]
I and @RafyAmgadBenjamin  create new command in jsx ``` threebot-flist``` 
you can create flist from docker image by passing 
 **It's your online creds**
- Application id
- username
- secret 
```python3
jsx threebot-flist --app_id Applicationid --secret SECRET --username USER_NAME
```
then it will upload both flist ( 3bot , 3bot-production)
@RafyAmgadBenjamin

**Comment by RafyAmgadBenjamin** [comment]
I and @BolaNasr  managed to create a ```toml``` file  that was merged with the flist we created from the container  to create a new ```flist``` and we were able to start ```threebot``` on zero os container. 

https://hub.grid.tf/nashaatp/threebot_startup.flist

**Comment by RafyAmgadBenjamin** [comment]
> use secret in script which is used on top of coreX

@despiegk Do you want us to start the ```threebot``` server using ```Corex``` with a secret?

**Comment by RafyAmgadBenjamin** [comment]
I have been investigating with @serboctor  In how we can start the threebot server using ```Corex```
we have found some issues related to ```Corex``` and we opened these issues to be solved
https://github.com/threefoldtech/jumpscaleX_core/issues/299
https://github.com/threefoldtech/jumpscaleX_core/issues/300
https://github.com/threefoldtech/jumpscaleX_core/issues/301

we tried to work around these issues and finally, we managed to run the ```threebot``` server using ```Corex```  but the mention issues need to be solved.

**Comment by BolaNasr** [comment]
Updated images of 3bot & 3bor_production by adding ```.startup.toml``` 
now you can create your flist without merging 
```python
jsx threebot-flist --app_id Applicationid --secret SECRET --username USER_NAME
```

============================================================================
create a JSX script to launch Threebot 
```
cd  /sandbox/code/github/threefoldtech/jumpscaleX_threebot/scripts
python3 threebot_launcher.py -i {ID} -s {SECRET} -f {YOUR_FLIST} -p {NODE_IP}
```

**Comment by despiegk** [comment]
note the branch name !!!
remove older branch names, make sure only mods done for this story is in branch
